[uwsgi]
# Who will run the code
uid = searxng
gid = searxng

# Number of workers
workers = 4
threads = 4

# The right granted on the created socket
chmod-socket = 666

# Plugin to use and interpreter config
single-interpreter = true
master = true
plugin = python3
lazy-apps = true
enable-threads = true

# Module to import
module = searx.webapp

# Virtualenv and python path
pythonpath = /usr/local/searxng
chdir = /usr/local/searxng

# Disable logging for privacy
disable-logging = true
log-5xx = true

# No request overhead
buffer-size = 8192

# Speeds up the unloading process
vacuum = true
